### ISSUE TITLE
无法加载，说没有 loguru 

### ISSUE THREAD

**Issue by Sylphinford** [H-K-Y/Genshin_Impact_bot#51]
怎么解

[2021-09-23 00:35:31,902 nonebot] ERROR: Failed to import "hoshino.modules.Genshin.query_resource_points", error: No module named 'loguru'
[2021-09-23 00:35:31,953 nonebot] ERROR: No module named 'loguru'
Traceback (most recent call last):
  File "C:\Users\illya\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\illya\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\Genshin\query_resource_points\__init__.py", line 3, in <module>
    from .query_resource_points import get_resource_map_mes,get_resource_list_mes,init_point_list_and_map
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\Genshin\query_resource_points\query_resource_points.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by H-K-Y** [comment]
安装loguru就行
pip install loguru
