### ISSUE TITLE
不自动下载图片资源导致[相遇之缘]等功能无法使用

### ISSUE THREAD

**Issue by joshefi** [H-K-Y/Genshin_Impact_bot#60]
国内服务不自动下载图片资源导致[相遇之缘]等功能无法使用

**Comment by H-K-Y** [comment]
发一下下载时的报错日志

**Comment by joshefi** [comment]
[2021-10-04 11:34:45,200 nonebot] ERROR: Failed to import "hoshino.modules.Genshin_Impact_bot.gacha", error: No module named 'loguru'
[2021-10-04 11:34:45,200 nonebot] ERROR: No module named 'loguru'

[2021-10-04 11:34:45,204 nonebot] INFO: Succeeded to import "hoshino.modules.Genshin_Impact_bot.almanac"
[2021-10-04 11:34:45,205 nonebot] ERROR: Failed to import "hoshino.modules.Genshin_Impact_bot.query_resource_points", error: No module named 'loguru'
[2021-10-04 11:34:45,205 nonebot] ERROR: No module named 'loguru'

**Comment by joshefi** [comment]
[2021-10-04 11:41:20,556 nonebot] ERROR: Failed to import "hoshino.modules.shebot.conhead", error: No module named 'cv2'
[2021-10-04 11:41:20,556 nonebot] ERROR: No module named 'cv2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/yuanshenbot/hoshino/modules/shebot/conhead/__init__.py", line 17, in <module>
    from .opencv import add
  File "/root/yuanshenbot/hoshino/modules/shebot/conhead/opencv.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
[2021-10-04 11:41:20,635 hoshino] ERROR: 缺少图片资源：/root/yuanshenbot/res/img/priconne/gadget/equip.png
[2021-10-04 11:41:20,635 chara] ERROR: [Errno 2] No such file or directory: '/root/yuanshenbot/res/img/priconne/gadget/equip.png'
Traceback (most recent call last):
  File "/root/yuanshenbot/hoshino/modules/priconne/chara.py", line 28, in <module>
    gadget_equip = R.img('priconne/gadget/equip.png').open()
  File "/root/yuanshenbot/hoshino/R.py", line 50, in open
    return Image.open(self.path)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/yuanshenbot/res/img/priconne/gadget/equip.png'
[2021-10-04 11:41:20,661 hoshino] ERROR: 缺少图片资源：/root/yuanshenbot/res/img/priconne/gadget/thumb-up-i.png
[2021-10-04 11:41:20,661 pcr-arena] ERROR: [Errno 2] No such file or directory: '/root/yuanshenbot/res/img/priconne/gadget/thumb-up-i.png'
Traceback (most recent call last):
  File "/root/yuanshenbot/hoshino/modules/priconne/arena/__init__.py", line 31, in <module>
    thumb_up_i = R.img('priconne/gadget/thumb-up-i.png').open().resize((16, 16), Image.LANCZOS)
  File "/root/yuanshenbot/hoshino/R.py", line 50, in open
    return Image.open(self.path)
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/yuanshenbot/res/img/priconne/gadget/thumb-up-i.png'
[2021-10-04 11:41:20,677 nonebot] ERROR: Failed to import "hoshino.modules.Genshin_Impact_bot.gacha", error: No module named 'loguru'
[2021-10-04 11:41:20,677 nonebot] ERROR: No module named 'loguru'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/gacha/__init__.py", line 2, in <module>
    from .gacha import gacha_info , FILE_PATH , Gacha , POOL
  File "/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/gacha/gacha.py", line 3, in <module>
    from .pool_data import POOL ,UP_PROBABILITY,POOL_PROBABILITY,DISTANCE_FREQUENCY
  File "/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/gacha/pool_data.py", line 3, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
[2021-10-04 11:41:20,682 nonebot] ERROR: Failed to import "hoshino.modules.Genshin_Impact_bot.query_resource_points", error: No module named 'loguru'
[2021-10-04 11:41:20,682 nonebot] ERROR: No module named 'loguru'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonebot/plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/query_resource_points/__init__.py", line 3, in <module>
    from .query_resource_points import get_resource_map_mes,get_resource_list_mes,init_point_list_and_map
  File "/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/query_resource_points/query_resource_points.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by Wansn-w** [comment]
> [2021-10-04 11:41:20,635 hoshino] ERROR: 缺少图片资源：/root/yuanshenbot/res/img/priconne/gadget/equip.png
[2021-10-04 11:41:20,635 chara] ERROR: [Errno 2] No such file or directory: '/root/yuanshenbot/res/img/priconne/gadget/equip.png'

这个报错，你看路径`/root/yuanshenbot/res/img/priconne/gadget/equip.png`和本项目路径`/root/yuanshenbot/hoshino/modules/Genshin_Impact_bot/`并非同一个....

从以上报错信息建议您运行此命令：
```
pip install loguru opencv-python
```

**Comment by joshefi** [comment]
Thanks a lot.我成功解决了此问题
