### ISSUE TITLE
查看体力值

### ISSUE THREAD

**Issue by 3273576540** [H-K-Y/Genshin_Impact_bot#95]
查看体力值指令
go-cq端报错风控
实际并未风控，刷副本指令都很正常

**Comment by 3273576540** [comment]
ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when get_user_stamina handling message 1212789204.
[2022-02-06 11:46:49,227 模拟刷本] ERROR: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\service.py", line 224, in wrapper
    return await func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\Genshin_Impact_bot\artifact_collect\__init__.py", line 227, in get_user_stamina
    await bot.send(ev, mes, at_sender=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

**Comment by Wansn-w** [comment]
唔 这一般是**风控**了哦 和gi bot本身没关系ww
